server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    context-path: /termit
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
      file-size-threshold: 0B
      location: ${java.io.tmpdir}
  profiles:
    active: @spring.profiles.active@

javamelody:
  init-parameters:
    authorized-users: admin:kral0vnat3rm1t1st3

keycloak:
  realm: kodi
  resource: termit
  realm-key: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArr54p7YsfjCKwPnKDXhIhOGJYds6rp3O02lc8fJyzguaXkhy3Mq1ywZT3gjYvPrfMz+wqck8A6F2I2VEGxsUJ+SC9cgX1TTEMPUQh3BWDf45DCZfvvShGZ+t1nxsVfEw7J7xndRSy0LFJo5G/lU3impSvyxV/ZX9PgdrbKeVnuKfL3DesqCc1bBsbBf4xRHKL2pIK3BFyRnsWQcGkZcl7p0wpn9uF4dzk1zZ+CTGCNp34CYo1dN3Az2n/pJfOF2gH1rYjjdAeiFZmzf83KJgcjBRZXfORrf6zO3pkMHR0JrexhbS/PJDr3HvlpLC+/ss/HCCCkFLyefykNadUZ+XOwIDAQAB"
  auth-server-url: "http://localhost:8080/auth"
  credentials:
    secret: "5c6ffe21-54dd-44dc-8d8b-f20f92891e79"

repository:
  url: https://graphdb.onto.fel.cvut.cz/repositories/kodi-uloziste-dev
persistence:
  driver: cz.cvut.kbss.ontodriver.sesame.SesameDataSource
  language: cs
jwt:
  secretKey: TermItSecretKey
namespace:
  vocabulary: http://onto.fel.cvut.cz/ontologies/slovnik/
  user: http://onto.fel.cvut.cz/ontologies/uzivatel/
  resource: http://onto.fel.cvut.cz/ontologies/zdroj/
file:
  storage: /tmp/termit
textAnalysis:
  url: http://localhost/annotace/annotate
