name: Compile and test

on:
  push:
    branches: [ dev, development ]
  pull_request:
    branches: [ main, dev, development ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt

    - name: Test
      run: mvn -B test
